networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_envmtv:
    image: xoxxox/envmtv:001
    container_name: xoxxox_envmtv
    env_file:
      - ./envdir.txt
    volumes:
      - ../../../export:/opt/common
      - ../../../strage:/opt/strage
      - ../../../import/cnnmmd_xoxxox_envmtv/envmtv/hgf:/home/usrapp/.cache/huggingface
      - ../../../import/cnnmmd_xoxxox_envmtv/envmtv/mes:/home/usrapp/.cache/mesa_shader_cache
    deploy:
      resources:
        limits:
          cpus: 3.0
          memory: 12G
    command: bash -c "/usr/sbin/sshd -D"
